# Generated by Django 3.1.14 on 2022-04-14 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_auto_20220411_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemonentity',
            options={'verbose_name': 'Особь', 'verbose_name_plural': 'Особи'},
        ),
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='appeared_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 14, 16, 0, 3, 404805), verbose_name='Появится'),
        ),
    ]
