# Generated by Django 3.1.14 on 2022-04-14 17:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_auto_20220414_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='evolve_from',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolve_to', to='pokemon_entities.pokemon', verbose_name='Из кого эволюционировал'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='appeared_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 14, 20, 55, 5, 481736), verbose_name='Появится'),
        ),
    ]
